### ISSUE TITLE
#Refactoring- make the default case one of the cases, otherwise try to remove code that does nothing if you can

### ISSUE THREAD

**Issue by HJackdeJong** [COMP2522/project-bombpers#100]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L102

**Comment by OzanYRT** [comment]
Thank you for pointing this out. We fixed it.
