### ISSUE TITLE
When Playing Game 2 keys can be pressed to double movement speed 

### ISSUE THREAD

**Issue by kavindail** [COMP2522/project-bombpers#102]
For example w and the up arrow will move you double the speed that was intended

**Comment by kavindail** [comment]
Could be fixed by disabling other movement keys when one is pressed

**Comment by breader1** [comment]
We'll look into this bug. Thanks Kavin.

**Comment by OzanYRT** [comment]
Deleted the duplicate moving method, now you can't move with both keys and double your speed. We may have another movement method for player move in the future.
