### ISSUE TITLE
Refactor conditional to not rely on local variable state 

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-bombpers#107]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L122

**Comment by breader1** [comment]
Ok, We'll look deeper into this one.

**Comment by OzanYRT** [comment]
Refactored to whole method to directly access and modify player position instead of local variables in window class that determines the position. Thank you for pointing this out Paul.

**Comment by OzanYRT** [comment]
The implementation we came up with wasn't correct, reopening the issue.
