### ISSUE TITLE
Update player direction should be in Player class

### ISSUE THREAD

**Issue by abhishekchouhannk** [COMP2522/project-bombpers#110]
The player direction is being managed in the window class right now

https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L107

but it should be in the player class itself and can be easily refactored

**Comment by breader1** [comment]
Good idea, Thank you.
