### ISSUE TITLE
Refactor to set state only once

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-bombpers#113]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L182

This is setting state over and over again. While not a big problem in this program, it's bad practice to get into. Typically we want to package state changes into single transactions, so try to emulate this here by instead using an accumulator and setting state once at the end of the loop.

**Comment by breader1** [comment]
We've refactored this part of the code! Thanks Paul.
