### ISSUE TITLE
Use named constants

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-bombpers#114]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L223

**Comment by pbucci** [comment]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Score.java#L37

for exactly this reason, now I'm not sure what a 1 means without the above context

**Comment by breader1** [comment]
We've addressed this and made the changes ! Thanks.
