### ISSUE TITLE
A compareTo method in the player class

### ISSUE THREAD

**Issue by abhishekchouhannk** [COMP2522/project-bombpers#125]
A compareTo method in player class does not sound right. 

https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Player.java#L34

What is the player being compare to? The enemeis? On what basis?, if player and enemy sizes are say being compared, just make a compareSize method just make it descriptive enough.

**Comment by bli129** [comment]
removed it due to being unused
