### ISSUE TITLE
Does not run on mac

### ISSUE THREAD

**Issue by amritjhatu** [COMP2522/project-bombpers#130]
I believe it is a gradle issue maybe? Try to figure out a way so my mac can actually run the game when brought over. 

It may also involve the source of the images and formatting that does not carry over.

"
<img width="879" alt="image" src="https://user-images.githubusercontent.com/113412608/228451485-1ae633b8-d984-4b47-8110-5e1c4521f2b3.png">
"

**Comment by breader1** [comment]
Verified with Paul, This is a non-issue.
