### ISSUE TITLE
Player can be singleton- A good design choice

### ISSUE THREAD

**Issue by abhishekchouhannk** [COMP2522/project-bombpers#133]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Player.java#L16

since only one instance of player exists in a class, it can be refactored to be made into a singleton class.

**Comment by breader1** [comment]
This is now implemented.

**Comment by abhishekchouhannk** [comment]
Nice!
