### ISSUE TITLE
Unused CompareTo Method

### ISSUE THREAD

**Issue by amritjhatu** [COMP2522/project-bombpers#140]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Comparable.java#L7

Maybe remove it or add a reasoning in comments why it is unused? It would be confusing for the average person should they have this code and need to look through it.

**Comment by bli129** [comment]
removed unused
