### ISSUE TITLE
Potential Null Pointer Exception Opportunity?

### ISSUE THREAD

**Issue by amritjhatu** [COMP2522/project-bombpers#141]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L123

Potential null pointer exception: The collectionManager.getPlayer() method is called in updatePlayerDirection() without checking if it is null. Could be a good idea to add a null check to avoid a potential null pointer exception?

**Comment by breader1** [comment]
This can't happen because the player is initialized in the setup() through the init() call.
