### ISSUE TITLE
Encapsulate the attributes in Player class

### ISSUE THREAD

**Issue by abhishekchouhannk** [COMP2522/project-bombpers#172]
https://github.com/COMP2522/project-bombpers/blob/b6dea351dd90d86988099d8cc5810beb4bd7aa61/src/main/java/org/bcit/comp2522/project/Player.java#L18

This and other attributes are set to public, just change them to private because this might get pointed out as "violating encapsulation" and other classes freely accessing other classes' attributes.

Should not be too big of an issue, cause I realized these are only being referenced in the player class itself, no need for getters and setters I guess.

**Comment by OzanYRT** [comment]
This doesn't violate encapsulation since variables are already constants and they can't be changed in other classes.
