### ISSUE TITLE
#Refactoring - State numbers should have better names to remove magic numbers

### ISSUE THREAD

**Issue by breader1** [COMP2522/project-bombpers#38]
https://github.com/COMP2522/project-bombpers/blob/0d4652c1cf54c42393b954b5850b38e9fe583a98/src/main/java/org/bcit/comp2522/project/Menu.java#L23

I think having state names like "PLAY","PAUSE","PLAYER_DEATH" etc would make it more clear regarding what the state of the game actually is.

We can use constants for this - I'm not sure exactly which states are which but this should give a general idea of what I'm trying to say here:
GAMEPLAY = 0;
PAUSE = 1;

switch(state){
    case PAUSE:
    //stuff to do when paused
    break;
    //etc.
}

**Comment by AmarjotS82** [comment]
Created a pull request resolving this issue

**Comment by breader1** [comment]
Your PR needs some changes before it can be merged
