### ISSUE TITLE
#Refactoring - Same method should be removed

### ISSUE THREAD

**Issue by breader1** [COMP2522/project-bombpers#39]
https://github.com/COMP2522/project-bombpers/blob/0d4652c1cf54c42393b954b5850b38e9fe583a98/src/main/java/org/bcit/comp2522/project/Menu.java#L49

https://github.com/COMP2522/project-bombpers/blob/0d4652c1cf54c42393b954b5850b38e9fe583a98/src/main/java/org/bcit/comp2522/project/Menu.java#L56

It seems like these methods are doing the same thing, can we remove button2() without breaking functionality?

**Comment by AmarjotS82** [comment]
The difference is the x and y position of the button2() and button() because there are two buttons that will be displayed on the screen but one is lower.  Button 2 is being called in the switch statement under the last case as another option.

**Comment by breader1** [comment]
If that's the case, we should have a Button class that takes x and y values as parameters for where they're displayed on screen. We don't want two different version of the same function.
