### ISSUE TITLE
#Refactoring - draw() method needs some trimming down

### ISSUE THREAD

**Issue by breader1** [COMP2522/project-bombpers#52]
https://github.com/COMP2522/project-bombpers/blob/2e549711d8aa24f810122b15a670719fbc160469/src/main/java/org/bcit/comp2522/project/Window.java#L133

A good place to start would be Create some helper functions for the different parts of the method. Is it is right now, this method is a major bloated. It may take a group effort to get this one done.

I good place to start could be looking at any type of loops and making those into helper functions.

**Comment by bli129** [comment]
Functionalities have been refactored into their appropriate classes, reducing the draw() method in window.
