### ISSUE TITLE
Move menu states into the menu class, create a menu instance in window to change the menu states

### ISSUE THREAD

**Issue by HJackdeJong** [COMP2522/project-bombpers#64]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L67

**Comment by OzanYRT** [comment]
Amarjot i think you already are done with this

**Comment by OzanYRT** [comment]
@AmarjotS82 Can you check if this is done or not?
