### ISSUE TITLE
#Refactoring- Show the end game score when the game is over

### ISSUE THREAD

**Issue by HJackdeJong** [COMP2522/project-bombpers#79]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Score.java#L52

**Comment by OzanYRT** [comment]
I think this is done.

**Comment by OzanYRT** [comment]
@AmarjotS82 Can you check if we already did this or not?
