### ISSUE TITLE
Consider deleting this unused CompareTo() method

### ISSUE THREAD

**Issue by nathanb1357** [COMP2522/project-bombpers#81]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Collidable.java#L9

The void CompareTo method is not used in any classes and takes up space to override

**Comment by OzanYRT** [comment]
Thank you for pointing this out. We have deleted them.
