### ISSUE TITLE
try to explain what case 1 and default case means

### ISSUE THREAD

**Issue by SimratKaur2** [COMP2522/project-bombpers#83]
you can add a comment or maybe make the case more descriptive such as a string that desribes what case 1 is supposed to do.
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Score.java#L37

**Comment by OzanYRT** [comment]
We changed cases having numbers to constant values. Now our code is more readable.
