### ISSUE TITLE
Get rid of magic numbers (0,1,2, 100, 120, 312, 199, 244, 90) 

### ISSUE THREAD

**Issue by sunminpark94** [COMP2522/project-bombpers#85]
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Window.java#L216

**Comment by OzanYRT** [comment]
We got rid of spawn types in window class and added them to their own class. For naming, we got rid of most of the numbers, instead, we are using constants to make the code more understandable.
