### ISSUE TITLE
Make switch cases more descriptive.

### ISSUE THREAD

**Issue by SimratKaur2** [COMP2522/project-bombpers#93]
Specify what each switch case is for, either by adding comments or having descriptive strings as cases.
https://github.com/COMP2522/project-bombpers/blob/dd1ddfb6e28bc42ed48da71f5d1fa044367e7975/src/main/java/org/bcit/comp2522/project/Menu.java#L24

**Comment by OzanYRT** [comment]
We don't have switch cases with numbers anymore, we use enums for MenuState now.
